apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: thoguppu
  labels:
    app: thoguppu
spec:
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: thoguppu:latest
